---
version: '2'

services:
  jenkins:
    image: 'jenkins/jenkins:2.361.3-jdk11'
    container_name: jenkins
    user: root
    restart: always
    ports:
      - '8080:8080'
      - '5000:5000'
    volumes:
      - /home/huupv/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
